### ISSUE TITLE
在3080ti上训练让Bert也参与训练内存溢出

### ISSUE THREAD

**Issue by DavidZha1994** [qingyujean/document-level-classification#6]
是不是当feature_extract设置为False的时候所有BERT实例都会参与训练，有什么办法可以在内存只有12G的一张显卡上让BERT也参与微调吗

**Comment by DavidZha1994** [comment]
problem fixed

**Comment by dengxiaotian123** [comment]
你好，请问这个项目的bert 那个模型您这边能顺利跑起来吗？会出现 nan 吗？

**Comment by DavidZha1994** [comment]
我后来参照了她的代码用pytorch lighting 又重写了一遍，BERT我没继续训练当然也实现了梯度累积模拟，但是让他只是提取特征就足够了，后来就没让BERT参与微调
